In [2]:
import sys
sys.path.append('../data')
from download_data import get_csv_path

import pandas as pd 

df =  pd.read_csv(get_csv_path(), nrows=50000)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Shape: (50000, 24)

Columns:
['id', 'name', 'album', 'album_id', 'artists', 'artist_ids', 'track_number', 'disc_number', 'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature', 'year', 'release_date']

In [3]:
df.head()

,id,name,album,album_id,artists,artist_ids,track_number,disc_number,explicit,danceability,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,year,release_date
0,7lmeHLHBe4nmXzuXc0HDjk,Testify,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],1,1,False,0.470,...,0.0727,0.02610,0.000011,0.3560,0.503,117.906,210133,4.0,1999,1999-11-02
1,1wsRitfRRtWyEapl0q22o8,Guerrilla Radio,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],2,1,True,0.599,...,0.1880,0.01290,0.000071,0.1550,0.489,103.680,206200,4.0,1999,1999-11-02
2,1hR0fIFK2qRG3f3RF70pb7,Calm Like a Bomb,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],3,1,False,0.315,...,0.4830,0.02340,0.000002,0.1220,0.370,149.749,298893,4.0,1999,1999-11-02
3,2lbASgTSoDO7MTuLAXlTW0,Mic Check,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],4,1,True,0.440,...,0.2370,0.16300,0.000004,0.1210,0.574,96.752,213640,4.0,1999,1999-11-02
4,1MQTmpYOZ6fcMQc56Hdo7T,Sleep Now In the Fire,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],5,1,False,0.426,...,0.0701,0.00162,0.105000,0.0789,0.539,127.059,205600,4.0,1999,1999-11-02

In [4]:
df.describe()

,track_number,disc_number,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,year
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,5.000000e+04,50000.00000,50000.000000
mean,7.414240,1.039380,0.496567,0.549326,5.237220,-11.181564,0.681620,0.087211,0.389191,0.276269,0.212796,0.438708,118.475457,2.504162e+05,3.84312,2002.787320
std,5.372275,0.244521,0.185222,0.287404,3.548678,6.383692,0.465852,0.127056,0.374373,0.371828,0.192665,0.266893,30.736595,1.510033e+05,0.55324,9.614427
min,1.000000,1.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+03,0.00000,1928.000000
25%,3.000000,1.000000,0.364000,0.310000,2.000000,-14.031000,0.000000,0.034400,0.021900,0.000010,0.097800,0.209000,95.363750,1.789948e+05,4.00000,1999.000000
50%,7.000000,1.000000,0.505000,0.573000,5.000000,-9.500000,1.000000,0.044300,0.256000,0.007900,0.129000,0.420000,117.805000,2.300000e+05,4.00000,2003.000000
75%,10.000000,1.000000,0.632000,0.804000,8.000000,-6.635000,1.000000,0.073600,0.786000,0.689000,0.268000,0.653000,137.440250,2.900275e+05,4.00000,2007.000000
max,50.000000,6.000000,0.987000,1.000000,11.000000,3.802000,1.000000,0.966000,0.996000,1.000000,1.000000,1.000000,231.028000,6.054655e+06,5.00000,2020.000000

In [5]:
df.isnull().sum()

id                  0
name                0
album               0
album_id            0
artists             0
artist_ids          0
track_number        0
disc_number         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
year                0
release_date        0
dtype: int64

In [1]:
import sys
import os

# Add the source/ and data/ folders to Python's import path
# so we can import our modules directly.
PROJECT_ROOT = os.path.abspath('..')   # if notebook is in notebooks/, project root is one level up
sys.path.append(os.path.join(PROJECT_ROOT, 'source'))
sys.path.append(os.path.join(PROJECT_ROOT, 'data'))

import pandas as pd
from preprocessing import preprocess, save_scaler
from download_data import get_csv_path

# Load 200 random rows for our first pipeline test
df = pd.read_csv(get_csv_path()).sample(n=200_000, random_state=42)


X, ids, scaler = preprocess(df)

print(f"X shape: {X.shape}")
print(f"X dtype: {X.dtype}")
print(f"# of IDs: {len(ids)}")
print(f"X[0]: {X[0]}")
print(f"X mean per col: {X.mean(axis=0)[:12]}")
print(f"X std per col: {X.std(axis=0)[:12]}")

save_scaler(scaler)

/Users/matt/Documents/school-comsc/CSE-108/Lab_9/Lab_9/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/matt/Documents/school-comsc/CSE-108/Lab_9/Lab_9/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
X shape: (199523, 24)
X dtype: float32
# of IDs: 199523
X[0]: [ 0.6837181   0.7678098   1.1722239  -1.4237669   2.7006228  -1.1551862
 -0.75050616 -0.7352191  -0.02669833 -0.9812875   0.81371087  0.30103382
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          1.        ]
X mean per col: [-5.7357254e-11 -2.8678629e-10 -2.1030994e-10 -5.6974874e-09
  2.1030994e-10 -5.8313210e-10  2.7913865e-09  5.3533439e-10
  3.8238170e-11  1.7207177e-10 -9.5595427e-11  5.3294449e-09]
X std per col: [1.         0.99999994 0.99999994 1.         1.         1.
 0.9999999  1.         1.         0.9999999  0.99999994 1.        ]

In [2]:
import os
print(os.getcwd())

/Users/matt/Documents/school-comsc/CSE-108/Lab_9/Lab_9/notebooks